spring:
  # Database
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Jpa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: false

server:
  port: 8080